### PR TITLE
allow composer/installers also in version 2.x

### PR DESCRIPTION
**Pull request by sfsmfc**
The dependecy composer/installers has update his supported types. Can we please also allow version 2.x?

### CODE REVIEW

**Comment by DuaelFr** [comment]
Yes, please ! <3

**Comment by eguerin-ucsf** [comment]
Yeah this is really needed as you can't use Composer 2 with composer/installer 1.0 as the API doesn't match.

**Comment by DieterHolvoet** [comment]
+1!

**Comment by jplana-ubc** [comment]
Please @balbuf 🙏

**Comment by Martin-P** [comment]
Would be great if this can be added, this fixes issue #37.

**Comment by axroth** [comment]
+1!

**Comment by kmajzlik** [comment]
Sure we need this ASAP.

**Review by ben-hamelin — APPROVED** [review]
Looks good, merging this in shortly and will tag a new release

**Comment by sfsmfc** [comment]
Hi,

thanks a lot. Can you please release a new tag for this changes?

**Comment by ben-hamelin** [comment]
@sfsmfc You're welcome!
 tagged 2.0.1

**Pull request merged**
