### PR TITLE
Add PSR-2, PHP 7 syntax, unit tests, CHANGELOG

### PR DESCRIPTION
**Pull request by nathandentzau**
## Description

This refactors the existing code base adding PSR-2 and PHP 7 syntax. With PHP 5.6 at EOL at the end of December, I think it's time to use the latest syntax in this project. Changes in this PR will cause BC issues and will require a version `2.x` to be tagged after it is merged in. I've also added unit tests using PHPUnit, PHPCS for linting the code base for PSR-2 standards and other files to support local development. A `CHANGELOG` has also been added to the project. The project has a functioning .travis.yml file that will need to be added to the `oomphinc` travis org.

### CODE REVIEW

**Comment by raubin** [comment]
I assigned this to you @balbuf since this is your baby! :)

**Comment by nathandentzau** [comment]
Hey @raubin what's the status on getting this merged in? :eyes:

**Comment by raubin** [comment]
Wow, this one goes way back @nathandentzau ! We'll get 👀 on it so we can get it closed out. Standby.

**Comment by nathandentzau** [comment]
Thank you @raubin! :)

**Review by raubin — APPROVED** [review]
A few things to tidy up on our side before a 2.0 release, but thank you for the review reminder @nathandentzau !

**Pull request merged**
